-- Intake Review TASK-5 ST001/ST002 (CL-094, CL-238)
ALTER TABLE "conversion_events"
  ADD COLUMN IF NOT EXISTS "manually_validated" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "validated_at" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "validated_by" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "amount_brl" DECIMAL(14, 2),
  ADD COLUMN IF NOT EXISTS "channel" VARCHAR(50);
